apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cqtv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-cqtv@sha256:570fed918e4c183d97144e9c5a8b3976dea047756ab27d2d2978ea472a8f0fdd
        name: my-nodejs
        resources: {}
status: {}
